# Configuration for your Go application
Host: "0.0.0.0"  # Replace with your desired host
Port: "8080"     # Replace with your desired port

# Other configuration settings
ProjectSettings:
  AppName: BasicTemplate
  LogAppender: application-log
  AlarmAppender: alarm-log
  MessageType: API_CALL
  MsName: GoAPIBasicTemplate

DTE.Log:
  Level: INFO
  RelativeFolderPath: INFO
  RollingInterval: Day
  RollOnFileSizeLimit: true
  MaxAge: 30
  MaxBackups: 3
  LocalTime: true
  Compress: true
  FileSizeLimitMegaBytes: 1

DTE.Alarm:
  Level: INFO
  RelativeFolderPath: INFO
  RollingInterval: Day
  RollOnFileSizeLimit: true
  MaxAge: 30
  MaxBackups: 3
  LocalTime: true
  Compress: true
  FileSizeLimitMegaBytes: 1